---
title: "Bees Colonies in USA"
author: "Aldo FERNANDEZ"
format: revealjs
editor: visual
---

```{r}
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(forcats)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggrepel)
library(sf)
library(maps)
library(mapdata)
library(usmap)
library(mapview)
```

```{r}
#Loading the data
colony <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-11/colony.csv')
origins_lost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-11/stressor.csv')
usa <- readr::read_csv('data/states.csv')
```

## Number of Bees Colonies in USA

```{r}
## Get the colonies totals for lost, added and final
# Not incluiding Hawaii
colonies_max <- colony |>
  filter(state != "Hawaii") |>
  select(state,colony_n, colony_lost, colony_added) |>
  group_by(state) |>
  summarise(colony_total = sum(colony_n,na.rm = TRUE),
         colony_lost_t = sum(colony_lost, na.rm = TRUE),
         colony_added_t = sum(colony_added, na.rm = TRUE)) |>
  inner_join(usa, join_by(state == state))

## Getting the percentage for the colonies
colonies_percent <- colony |>
  select(state, colony_n, colony_lost_pct, colony_reno_pct) |>
  group_by(state) |>
  summarise(
    colony_total = round(mean(colony_n, na.rm = TRUE)),
    lost_pct = round(mean(colony_lost_pct, na.rm = TRUE)),
    added_pct = round(mean(colony_reno_pct, na.rm = TRUE))) |>
    inner_join(usa, join_by(state == state))
world <- ne_countries(scale = "medium", returnclass = "sf")
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
```

```{r}
#Get the data from datasets to plot USA maps
world <- ne_countries(scale = "medium", returnclass = "sf")
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))

# Use the unicode for the bees, also using a geom_point for the bees
states|>
    ggplot() +
    geom_sf() +
    geom_point(data = colonies_max, aes(x = longitude, y = latitude, size = colony_total),shape = "\U1F41D") +
  geom_text_repel(data = colonies_max, aes(longitude, latitude,label =  code)) +
  scale_size_continuous(labels = scales::label_number_si(scale = 1e-6, suffix = " M")) +
  labs(size = "Colonies", x='',y='')

```

---

### 10 states with most bees colonies

```{r}
top_10_colonies <- colonies_max |>
  arrange(desc(colony_total)) |>
  head(10)

# Get the top 10 states with more bees, and change the scales for Millions

ggplot() +
    geom_sf(data = states) +
    geom_point(data = top_10_colonies, aes(x = longitude, y = latitude, size = colony_total),shape = "\U1F41D") +
  coord_sf(xlim = c(-130, -60), ylim = c(20, 60), expand = FALSE) +
  geom_text_repel(data = top_10_colonies, aes(longitude, latitude,label = state), nudge_x = c(3, 2, 2, 2, -1), nudge_y = c(0.25,-0.25, 0.5, 0.5, -0.5)) +scale_size_continuous(labels = scales::label_number_si(scale = 1e-6, suffix = " M"))+
  labs(size = "Colonies",x='',y='')
```

---

### 10 states with most bees lost

```{r}
top_10_lost <- colonies_max |>
  arrange(colony_lost_t) |>
  head(10)

## Show the 10 states with less bees
ggplot() +
    geom_sf(data = states) +
    geom_point(data = top_10_lost, aes(x = longitude, y = latitude, size = colony_lost_t),shape = "\U1F41D") +
  coord_sf(xlim = c(-130, -60), ylim = c(20, 60), expand = FALSE) +
  geom_text_repel(data = top_10_lost, aes(longitude, latitude,label = state)) +
  scale_size_continuous(labels = scales::label_number_si(scale=1e-3,suffix = 'K')) +
  labs(size = "Colonies",x='',y='')
```

---

### Bees colonies by year on USA

```{r}
## Plot in which year there were lees
colony |>
  filter(year != 2021) |>
  filter(state == "United States") |>
  group_by(year) |>
  summarise(colony_max_n = sum(colony_n-colony_lost,na.rm=TRUE))|>
  ggplot(aes(x=year, y=colony_max_n)) +
  geom_line(color="red") +
  labs(x = '',y='Bees count') +
  scale_y_continuous(labels = scales::label_number(suffix=" M", scale = 1e-6)) 
```

----

### Causes of death in bees colonies

```{r}
origins_lost$stressor <- factor(origins_lost$stressor)

sum_stressors <- origins_lost |>
  group_by(stressor) |>
  summarise( pct_stressor = mean(stress_pct, na.rm = TRUE)) |>
  group_by(stressor = ifelse(stressor %in% c("Other", "Unknown"), "Other", as.character(stressor))) %>%
  summarize(pct_stressor = sum(pct_stressor))


sum_stressors %>%
  ggplot(aes(x = fct_rev(fct_reorder(stressor, pct_stressor)), y = pct_stressor)) +
  geom_col(aes(fill = pct_stressor)) +
  labs( y="", x ="" , caption = "Mean of causes of death") +
  theme(legend.position = "none")
```

------------

### Bees lost by bimester

```{r}
colony$months <-factor(colony$months) 

colony |>
  filter(state != "United States") |>
  filter(year != 2021)|>
  group_by(year, months) |>
  summarise(sum_lost = sum(colony_lost, na.rm = TRUE))|>
  ggplot(aes(x = fct_rev(fct_reorder(months,sum_lost)) ,y=sum_lost)) +
  facet_wrap(~year)+
  geom_col(aes(fill = sum_lost)) +
  theme(legend.position = "none")+
  labs(x ="", y="") +
  theme(axis.text.x = element_text(angle = 90)) +
   scale_y_continuous(labels = scales::label_number(suffix=" K", scale = 1e-3))
```

## Colony renovation over lost by year

```{r}
clean_data <- na.omit(colony)

top_10_lost |> 
  #filter(year != 2021) |>
  #filter(state == "California")|>
  ggplot(aes(x=colony_lost_t ,y=colony_added_t))+
  scale_x_log10() +
  geom_point() +
  geom_smooth(alpha = 0.7, fullrange = TRUE ) +
  labs(x = 'Colonies lost', y = 'Colonies renovated', color = 'Months') +
  theme(legend.position = "none") +
  facet_wrap(~state)
```

------------------------------------------------------------------------

```{r}
colony |>
  filter(year != 2021) |>
  ggplot(aes(x = colony_lost,y = colony_added, fill = year)) +
  geom_boxplot(trim = FALSE)+
  scale_x_log10() +
  facet_wrap(~year) +
  theme(legend.position = "none")
```
